name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: erpsystemdemowebapp
  WORKING_DIRECTORY: .

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ERPSystem
    - name: Build
      run: dotnet build --no-restore
      working-directory: ERPSystem
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ERPTest
    #- name: Publish
    #  run: dotnet publish ERPSystem/ERPSystem.csproj -c Release -o website
    #- name: 'Deploy to Azure WebApp'
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    publish-profile: ${{ secrets.ERP_SYSTEM_DEMO_WEBAPP_SECRET }}
    #    package: '${{ env.WORKING_DIRECTORY }}/website'